spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: container_booking
      username: cassandra
      password: cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      session-name: cassandraSession

  application:
    name: container-booking-service
    init:
      order: 1